### ISSUE TITLE
[Feature Request] Use own SponsorBlock userid

### ISSUE THREAD

**Issue by MPThLee** [Galactic-Dev/iSponsorBlock#42]
**Is your feature request related to a problem? Please describe.**
Since submitted segment can be tracked via db viewer or their api, If there’s feature it will be nice. Some people just submit segment for stats.

**Describe the solution you'd like**
Generate user id randomly first time, then make viewable and changeable too.

**Additional context**
Other implementation(include official browser side implementation) has viewable and changeable uid feature.

**Comment by Galactic-Dev** [comment]
i'll add this to the list for the next update

**Comment by ego-lay-atman-bay** [comment]
This is already possible, if you have a jailbroken device anyway. I was able to find the configuration file and change the userid to my own, and then all my submissions go to my userid. Of course, I would still love it if this was added to the gui in isponsorblock, since I don't think everone wants to find the file thay contains the userid.

oh, and here's the path
```
<youtube data directory>/Documents/iSponsorBlock.plist
```
Of course I'm using uyouplus, so idk if it's different for the tweak.

**Comment by MPThLee** [comment]
Well, I'm not using jailbroken device. Sadly.
I read the implementation code and it writes a random-generated user id to settings file at first time of launch as it should be 'same' for every submission when it made. I'm hoping to see a GUI field of it.

**Comment by iCrazeiOS** [comment]
implemented in 7c1613839d28d75a6adc980f4abaa04229eef813. will have a v1.2 build "soon"
